# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
dist: trusty
group: edge
cache: packages

before_install:
- sudo apt-get update

after_success:
- Rscript -e 'covr::codecov()'
